# Generated by Django 4.2.3 on 2023-08-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_address_landmark_and_more'),
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user_address'),
        ),
    ]
