# Generated by Django 4.2.3 on 2023-08-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
