# Generated by Django 4.2.3 on 2023-08-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='delivery_date',
            new_name='status_modified_date',
        ),
    ]
