# Generated by Django 4.2.3 on 2023-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orders_coupon_applied_orders_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
