# Generated by Django 4.2.3 on 2023-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_coupons_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='maximum_discount',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='minimum_amount_required',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
