# Generated by Django 4.2.3 on 2023-08-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_coupons_maximum_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_applied_users',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
            preserve_default=False,
        ),
    ]
