# Generated by Django 4.2.3 on 2023-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_wallet_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
