# Generated by Django 4.2.3 on 2023-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_user_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
