# Generated by Django 4.2.3 on 2023-08-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_user_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cancellation_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reason', models.CharField(max_length=30)),
                ('order_status', models.CharField(choices=[('cancel', 'cancel'), ('return', 'return')])),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
