# Generated by Django 4.2.3 on 2023-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_cancellation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='public_coupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_cancellation_message',
            name='order_status',
            field=models.CharField(choices=[('  ', 'cancel'), ('return', 'return')]),
        ),
    ]
