# Generated by Django 4.2.3 on 2023-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_coupons_public_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cancellation_message',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('return', 'return')]),
        ),
    ]
