# Generated by Django 4.2.3 on 2023-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=9, max_length=15),
            preserve_default=False,
        ),
    ]
