# Generated by Django 4.2.3 on 2023-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='landmark',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
