# Generated by Django 4.2.3 on 2023-07-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size_stock',
            unique_together={('product', 'size')},
        ),
    ]
