# Generated by Django 4.2.3 on 2023-07-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
