# Generated by Django 4.2.3 on 2023-07-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='active',
            new_name='status',
        ),
    ]
