# Generated by Django 4.2.3 on 2023-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
