# Generated by Django 4.2.3 on 2023-08-05 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_product_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_cart',
            unique_together={('user', 'product')},
        ),
    ]
