# Generated by Django 4.2.3 on 2023-08-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product_cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('none', 'none'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product_cart',
            unique_together={('user', 'product', 'size')},
        ),
    ]
