# Generated by Django 4.2.3 on 2023-08-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_cart_unique_together_product_cart_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'size')},
        ),
    ]
