# Generated by Django 4.2.3 on 2023-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Both', 'BOTH')], default='Both', max_length=12),
        ),
    ]
