# Generated by Django 4.2.3 on 2023-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_products_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
                ('thumbnail_type', models.CharField(choices=[('square', 'square'), ('sixteen_nine', 'sixteen_nine'), ('banner', 'banner')], default='banner', max_length=20)),
            ],
        ),
    ]
