# Generated by Django 4.2.3 on 2023-09-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_banners_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='thumbnail_type',
        ),
    ]
